config/routes.rb
Rails.application.routes.draw do
  resources :user_listings
  resources :user_reports

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/cardcheck/' => 'user_listings#cardcheck', :defaults => { :format => 'json' }
  post '/rate/' => 'users#rate', :defaults => { :format => 'json' }
  get '/users/:id' => 'users#show', as: :showuser
  put '/users/:id' => 'users#update', as: :updateuser
  get '/pages/search_results/' => 'pages#search_results', as: :search
  get '/pages/card/' => 'pages#card', as: :card
  get '/pages/allcards/' => 'pages#allcards', as: :allcards
  get '/pages/setcards/' => 'pages#setcards', as: :setcards
  get '/traders/' => 'pages#traders', as: :traders
  end

app/views/pages/allcards.html.erb
<% @sets.each do |s|	%>
<%= link_to setcards_path(sn: s[1]) do %>
<p><%= s[0]	%></p>
<% end %>
<% end -%>

app/views/pages/card.html.erb
<%= @carddd[0]	%>



<div class ="row">
	<div class="col-md-3">
		<img id="cardImg" src= "<%=@carddd[1]%>">
	</div>
	<div class="col-md-4">
		<h4><%= @carddd[0]	%></h4>
		<div class="row">
			<div class="col-md-12">
				<p><%= @carddd[2]	%></p>
			</div>	
		</div>
	</div>

</div>


<% if !@listings.empty? %>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Trader Name</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Quantity Available</th>
      <th>Contact Seller</th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each_with_index do |listing,index|%>
      <tr>
      	<td><%=listing.user.name%></td>
      	<td><%=listing.condition%></td>
          <td><%=listing.price%></td>
      	<td><%=listing.quantity%></td>
		<td>
      <% if user_signed_in? %>
			<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#contact<%=index%>">
	  			Contact Seller
			</button>
      <% else %>
      <p>Sign in to contact the seller</p>
      <% end %>
		</td>
      	<div class="modal fade" id="contact<%= index	%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      	  <div class="modal-dialog" role="document">
      	    <div class="modal-content">
      	      <div class="modal-header">
      	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      	        <h4 class="modal-title" id="myModalLabel"><%=listing.user.name%></h4>
      	      </div>
      	      <div class="modal-body">
      	        <%=listing.user.location%>
      	        <%=listing.user.email%>
      	        <%=listing.user.contact_number%>
      	      </div>
      	      <div class="modal-footer">
      	      	<%= link_to('See Profile',showuser_path(listing.user), :class=>"btn btn-info") %>
      	      </div>
      	    </div>
      	  </div>
      	</div>
      </tr>
    <% end %>
  </tbody>
</table>



<% end %>

app/views/pages/home.html.erb
<!-- wala pang featured, trending and popular. idk if ill do those -->
<h2>New Cards</h2>
<!--2rowsof10cards-->
<% if !@new.empty?	%>

<% @new.each_with_index do |n, index| %>
<% card = MTG::Card.where(name: n[0]).all.map{|f| [f.name, f.image_url, f.text]}%>
<div class="col-md-2" id="cl<%=index%>">
	<%= link_to card_path(cn: card[0][0]) do %>
	<img id="cardImg" src= "<%=card[0][1]%>">
	<% end %>
</div>
	<% end %>
<%else%>
<h3>No new cards</h3>
	<% end %>

app/views/pages/search_results.html.erb
<h1>Results for <%= params[:search]	%></h1>

<!-- good luck front end person -->
<% @results.each do |r|	%>

<div class ="row">
	<div class="col-md-3">
		<%= link_to card_path(cn: r[0]) do %>
		<img id="cardImg" src= "<%=r[1]%>">
		<% end %>
	</div>
	<div class="col-md-4">
		<h4><%= r[0]	%></h4>
		<div class="row">
			<div class="col-md-12">
				<p><%= r[2]	%></p>
			</div>	
		</div>
	</div>

</div>
	<% end -%>



	<%= will_paginate @results %>

app/views/pages/setcards.html.erb
<h1><%= params[:sn]	%> Cards</h1>

<!-- good luck front end person -->
<% @setcards.each do |r|	%>

<div class ="row">
	<div class="col-md-3">
		<%= link_to card_path(cn: r[0]) do %>
		<img id="cardImg" src= "<%=r[1]%>">
		<% end %>
	</div>
	<div class="col-md-4">
		<h4><%= r[0]	%></h4>
		<div class="row">
			<div class="col-md-12">
				<p><%= r[2]	%></p>
			</div>	
		</div>
	</div>

</div>
	<% end -%>



	<%= will_paginate @setcards %>

app/views/pages/traders.html.erb
<h1>Traders</h1>	


<%@traders.each do |t|%>

<div class ="row panel panel-default">
	<div class="col-md-3">
		<%= image_tag t.avatar.url(:medium) %>
	</div>
	<div class="col-md-4 ">
		<%= link_to showuser_path(t) do	%>
		<div class="panel-heading"><%= t.name	%> <div class="overall-rating">
    (Average Rating <span id="avgrat"><%= "%.2f" % t.average_rating %></span> Based on <span id="totalrat"><%= t.total_rating.to_i %></span>  rating/s)
</div></div> <% end -%>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-12 panel panel-default">
					<p><%= t.description	%></p>
				</div>	
				<p><%= t.location%></p>
			</div>
		</div>
	</div>

</div>
<% end %>

<%= will_paginate @traders %>