config/routes.rb
Rails.application.routes.draw do
  resources :user_listings
  resources :user_reports

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/cardcheck/' => 'user_listings#cardcheck', :defaults => { :format => 'json' }
  post '/rate/' => 'users#rate', :defaults => { :format => 'json' }
  get '/users/:id' => 'users#show', as: :showuser
  put '/users/:id' => 'users#update', as: :updateuser
  get '/pages/search_results/' => 'pages#search_results', as: :search
  get '/pages/card/' => 'pages#card', as: :card
  get '/pages/allcards/' => 'pages#allcards', as: :allcards
  get '/pages/setcards/' => 'pages#setcards', as: :setcards
  get '/traders/' => 'pages#traders', as: :traders
  end

app/models/user_report.rb
class UserReport < ApplicationRecord
  belongs_to :user
end

app/controllers/user_reports_controller.rb
class UserReportsController < ApplicationController
  before_action :set_user_report, only: [:show, :edit, :update, :destroy]

  # GET /user_reports
  # GET /user_reports.json
  def index
    @user_reports = UserReport.all
  end

  # GET /user_reports/1
  # GET /user_reports/1.json
  def show
  end

  # GET /user_reports/new
  def new
    @user_report = UserReport.new
  end

  # GET /user_reports/1/edit
  def edit
  end

  # POST /user_reports
  # POST /user_reports.json
  def create
    @user_report = UserReport.new(user_report_params)

    respond_to do |format|
      if @user_report.save
        format.html { redirect_to @user_report, notice: 'User report was successfully created.' }
        format.json { render :show, status: :created, location: @user_report }
      else
        format.html { render :new }
        format.json { render json: @user_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_reports/1
  # PATCH/PUT /user_reports/1.json
  def update
    respond_to do |format|
      if @user_report.update(user_report_params)
        format.html { redirect_to @user_report, notice: 'User report was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_report }
      else
        format.html { render :edit }
        format.json { render json: @user_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_reports/1
  # DELETE /user_reports/1.json
  def destroy
    @user_report.destroy
    respond_to do |format|
      format.html { redirect_to user_reports_url, notice: 'User report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_report
      @user_report = UserReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_report_params
      params.require(:user_report).permit(:reason, :reporter, :user_id)
    end
end

app/helpers/user_reports_helper.rb
module UserReportsHelper
end

app/views/user_reports/_form.html.erb
<%= simple_form_for(@user_report) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :reason %>
    <%= f.input :reporter %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_reports/edit.html.erb
<h1>Editing User Report</h1>

<%= render 'form', user_report: @user_report %>

<%= link_to 'Show', @user_report %> |
<%= link_to 'Back', user_reports_path %>

app/views/user_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Reports</h1>

<table>
  <thead>
    <tr>
      <th>Reason</th>
      <th>Reporter</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_reports.each do |user_report| %>
      <tr>
        <td><%= user_report.reason %></td>
        <td><%= user_report.reporter %></td>
        <td><%= user_report.user %></td>
        <td><%= link_to 'Show', user_report %></td>
        <td><%= link_to 'Edit', edit_user_report_path(user_report) %></td>
        <td><%= link_to 'Destroy', user_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Report', new_user_report_path %>

app/views/user_reports/new.html.erb
<h1>New User Report</h1>

<%= render 'form', user_report: @user_report %>

<%= link_to 'Back', user_reports_path %>

app/views/user_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reason:</strong>
  <%= @user_report.reason %>
</p>

<p>
  <strong>Reporter:</strong>
  <%= @user_report.reporter %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_report.user %>
</p>

<%= link_to 'Edit', edit_user_report_path(@user_report) %> |
<%= link_to 'Back', user_reports_path %>