config/routes.rb
Rails.application.routes.draw do
  resources :user_listings
  resources :user_reports

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/cardcheck/' => 'user_listings#cardcheck', :defaults => { :format => 'json' }
  post '/rate/' => 'users#rate', :defaults => { :format => 'json' }
  get '/users/:id' => 'users#show', as: :showuser
  put '/users/:id' => 'users#update', as: :updateuser
  get '/pages/search_results/' => 'pages#search_results', as: :search
  get '/pages/card/' => 'pages#card', as: :card
  get '/pages/allcards/' => 'pages#allcards', as: :allcards
  get '/pages/setcards/' => 'pages#setcards', as: :setcards
  get '/traders/' => 'pages#traders', as: :traders
  end

app/models/user_listing.rb
class UserListing < ApplicationRecord
	belongs_to :user
	validates :card_name, :quantity, :condition,  :price,presence: true

	
end

app/controllers/user_listings_controller.rb
class UserListingsController < ApplicationController
  before_action :set_user_listing, only: [:show, :edit, :update, :destroy]

  # GET /user_listings
  # GET /user_listings.json
  def index
    @user_listings = UserListing.all
  end

  # GET /user_listings/1
  # GET /user_listings/1.json
  def show
  end

  def cardcheck
    @card = MTG::Card.where(name: params[:cn]).all


    respond_to do |format|
      if @card.present?
        if @card.count == 1
          format.json { render json: @card.map{|f| [f.name, f.image_url, f.text]} }
        else
          format.json { render json: @card.map{|f| [f.name, f.image_url, f.text]} }
        end
      else
        format.json { render json: 'null'}
      end
    end
  end

  # GET /user_listings/new
  def new
    @user_listing = UserListing.new

  end

  # GET /user_listings/1/edit
  def edit
  end

  # POST /user_listings
  # POST /user_listings.json
  def create
    @user_listing = current_user.user_listings.new(user_listing_params)


    respond_to do |format|
      if @user_listing.save
        format.html { redirect_to @user_listing, notice: 'User listing was successfully created.' }
        format.json { render :show, status: :created, location: @user_listing }
      else
        format.html { render :new }
        format.json { render json: @user_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_listings/1
  # PATCH/PUT /user_listings/1.json
  def update
    respond_to do |format|
      if @user_listing.update(user_listing_params)
        format.html { redirect_to @user_listing, notice: 'User listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_listing }
      else
        format.html { render :edit }
        format.json { render json: @user_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_listings/1
  # DELETE /user_listings/1.json
  def destroy
    @user_listing.destroy
    respond_to do |format|
      format.html { redirect_to user_listings_url, notice: 'User listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_listing
      @user_listing = UserListing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_listing_params
      params.require(:user_listing).permit(:card_name, :quantity, :condition, :price)
    end
end

app/helpers/user_listings_helper.rb
module UserListingsHelper
end

app/views/user_listings/_form.html.erb
<%= simple_form_for(@user_listing) do |f| %>
<%= f.error_notification %>
<div class="row">
  <div class="cardimage media col-md-3"></div>
  <div class="carddesc col-md-3"></div>
</div>
<div class="form-inputs">
  <div class="row">
    <div class="col-md-3">
      <%= f.input :card_name%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :quantity %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :condition, collection: ['Near Mint','Slightly Played','Moderately Played','Heavily Played','Damaged','Near Mint Foil','Slightly Played Foil','Moderately Played Foil','Heavily Played Foil','Damaged Foil'] %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <%= f.input :price %>
    </div>
  </div>
</div>
<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>



<script type="text/javascript">
$(document).ready(function(){
  $('.combobox1').combobox();
});
</script>



<script>
var typingTimer;                //timer identifier
var doneTypingInterval = 400;
$("#user_listing_card_name").on('keyup', function () {
  clearTimeout(typingTimer);
  typingTimer = setTimeout(doneTyping, doneTypingInterval);
});

$("#user_listing_card_name").on('keydown', function () {
  
  clearTimeout(typingTimer);
});

function doneTyping () {

  var s = $("#user_listing_card_name").val()
  , e = s.toString().length;

  e > 2 ? $.ajax({
    method: "GET",
    url: "/cardcheck/",
    data: {cn:s},
    dataType: "json",
    success: function(s) {
      s != null ? (
        console.log(s),
        $('.cardimage #cardImg').remove(),
        $('.carddesc #cardDesc').remove(),
        $("<img id=\"cardImg\""+ "src=\"" + s[0][1] + "\"/>").appendTo( $( ".cardimage" ) ),
        $("<p id=\"cardDesc\""+ ">\"" + s[0][2] + "\"</p>").appendTo( $( ".carddesc" ) )
        )
      : console.log("cant find it yo")
    }
  }) : null
}


</script>

app/views/user_listings/edit.html.erb
<h1>Editing User Listing</h1>

<%= render 'form', user_listing: @user_listing %>

<%= link_to 'Show', @user_listing %> |
<%= link_to 'Back', user_listings_path %>

app/views/user_listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Listings</h1>

<table>
  <thead>
    <tr>
      <th>Card name</th>
      <th>Quantity</th>
      <th>Condition</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_listings.each do |user_listing| %>
      <tr>
        <td><%= user_listing.card_name %></td>
        <td><%= user_listing.quantity %></td>
        <td><%= user_listing.condition %></td>
        <td><%= user_listing.price %></td>
        <td><%= link_to 'Show', user_listing %></td>
        <td><%= link_to 'Edit', edit_user_listing_path(user_listing) %></td>
        <td><%= link_to 'Destroy', user_listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Listing', new_user_listing_path %>

app/views/user_listings/new.html.erb
<h1>New User Listing</h1>

<%= render 'form', user_listing: @user_listing %>

<%= link_to 'Back', user_listings_path %>

app/views/user_listings/show.html.erb
<p id="notice"><%= notice %></p>
<% @cardd = MTG::Card.where(name: @user_listing.card_name).all.map{|f| [f.name, f.image_url, f.text]}%>
<%= image_tag @user_listing.user.avatar.url(:medium) %>
<div class ="row">
	<div class="col-md-3">
		<img id="cardImg" src= "<%=@cardd[0][1]%>">
	</div>
	<div class="col-md-4">
		<h4><%= @cardd[0][0]	%></h4>
		<div class="row">
			<div class="col-md-12">
				<p><%= @cardd[0][2]	%></p>
			</div>	
		</div>
	</div>

</div>


<%= @user_listing.user.name %>
<%= @user_listing.user.location %>

<p>
  <strong>Card name:</strong>
  <%= @user_listing.card_name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @user_listing.quantity %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @user_listing.condition %>
</p>

<p>
  <strong>Price:</strong>
  <%= @user_listing.price %>
</p>

<%= link_to 'Edit', edit_user_listing_path(@user_listing) %> |
<%= link_to 'Back', user_listings_path %>