config/routes.rb
Rails.application.routes.draw do
  resources :user_listings
  resources :user_reports

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/cardcheck/' => 'user_listings#cardcheck', :defaults => { :format => 'json' }
  post '/rate/' => 'users#rate', :defaults => { :format => 'json' }
  get '/users/:id' => 'users#show', as: :showuser
  put '/users/:id' => 'users#update', as: :updateuser
  get '/pages/search_results/' => 'pages#search_results', as: :search
  get '/pages/card/' => 'pages#card', as: :card
  get '/pages/allcards/' => 'pages#allcards', as: :allcards
  get '/pages/setcards/' => 'pages#setcards', as: :setcards
  get '/traders/' => 'pages#traders', as: :traders
  end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metatrade</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <nav class="navbar navbar-default" role="navigation">
    <!-- temp navbar hehe -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">MetaTrade</a>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to root_path do %>Home<% end %></li>
        <li><%= link_to allcards_path do %>Cards</li><% end %>
        <li><%= link_to traders_path do %>Traders<% end %></li>


        <%= form_tag(search_path, method: 'get', class: 'navbar-form navbar-left') do %>
          <%= search_field_tag 'search', nil, class: 'form-control', placeholder: 'Search'  %>
          <%= submit_tag "Submit", class: 'btn btn-default', :name => nil %>
        <% end %>




        <% if user_signed_in? %>
        <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown">Welcome, <%=current_user.name%>! <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "View Profile", showuser_path(current_user)%> </li>
                      <li><%= link_to "Edit Account", edit_user_registration_path%> </li>
                      <li><%= link_to "Logout", destroy_user_session_path, method: :delete%> </li>
                    </ul>
        </li>
        <% else %>
        <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown">Welcome, guest! <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Sign up", new_user_registration_path%></li>
                      <li><%= link_to "Login", new_user_session_path  %> </li>
                    </ul>
        </li>
        <% end %>


        
        <li><%= link_to new_user_listing_path do %>Create a Listing<% end %></li>
        
      </ul>
    </div>
  </nav>

  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
</body>
</html>